### ISSUE TITLE
After clicking the page (next page), HTTPS will become http. Why?

### ISSUE THREAD

**Issue by RockyQu** [fongandrew/hydeout#49] opened 2018-09-10 03:57 UTC

**Comment by RockyQu** [comment] 2018-09-10 04:33
It turns out that only on Chrome, HTTPS is redirected to http, which may be Chrome's problem. I'll try setting up Chrome to see if it works.

**Comment by RockyQu** [comment] 2018-09-10 04:34
Maybe it's not your blog.

**Comment by fongandrew** [comment] 2018-09-17 00:35
Closing since I can't reproduce. Feel free to open a new issue if you have a repro.

**Closed by fongandrew** 2018-09-17 00:36 UTC
